global:
  port: "${PORT:-9100}"
  sleep_seconds: ${SLEEP_SECONDS:-15}

networks:
  surge_hoodi:
    rpc: "https://l2-rpc.staging.surge.wtf"
    chain_id: "763374"
    addresses:
      wallet: "0x3bc256069FF9af461F3e04494A3ece3f62F183fC"

  surge_hoodi_staging:
    rpc: "https://l2-rpc.hoodi.surge.wtf"
    chain_id: "763375"
    addresses:
      wallet_surge: "0x3bc256069FF9af461F3e04494A3ece3f62F183fC"
