version: "3.9"
services:
  ethexporter:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    platform: linux/amd64
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    environment:
      CONFIG_FILE: "/app/config.yaml"

      # Mainnet
      NETWORK_MAINNET_RPC: "https://eth-mainnet.public.blastapi.io"
      NETWORK_MAINNET_CHAIN_ID: "1"

      # Surge Hoodi
      NETWORK_HOODI_RPC: "https://l2-rpc.staging.surge.wtf"
      NETWORK_HOODI_CHAIN_ID: "763374"

      # Surge Hoodi Staging
      NETWORK_HOODI_STAGING_RPC: "https://l2-rpc.hoodi.surge.wtf"
      NETWORK_HOODI_STAGING_CHAIN_ID: "763375"

    ports:
      - "9100:9100"
    restart: unless-stopped
